### ISSUE TITLE
Workaround to compile with monaca.io

### ISSUE THREAD

**Issue by zabeliqbal** [AyogoHealth/cordova-plugin-update-notifier#15]
Tried to compile android package using monaca but unsuccessful because monaca is using Gradle 6.5 . If you facing the same issues, try to change google material to 1.5.0-alpha02 .

change line 66 in plugin.xml to :
<framework src="com.google.android.material:material:[1.0.0,1.5.0-alpha02)" /> 

This one work for me..

**Comment by jpike88** [comment]
related to #16. I have done the above and it works

**Comment by dpogue** [comment]
As of version 2.0.1, the plugin specifies `"com.google.android.material:material:[1.0.0,1.5.0)"` which should not allow using any alpha or beta version of 1.5.0 (which requires Android SDK 31, which is not currently supported by Cordova Android).

I suggest uninstalling and reinstalling v2.0.1 of this plugin to ensure it uses the correct com.google.material dependency.

**Comment by jpike88** [comment]
> which should not allow using any alpha or beta version of 1.5.0 

Yet it does. So the above statement is incorrect, and so this issue should remain open.

I've tested with the above tweak and it works for my Android build, so I've forked until this is recognised as a problem.
