### ISSUE TITLE
Builiding the application fails

### ISSUE THREAD

**Issue by psjanwilmar** [AyogoHealth/cordova-plugin-update-notifier#16]
I tried to build a release but it fails.

![image](https://user-images.githubusercontent.com/78345816/134474748-5e2dda9e-f996-49a8-b4a2-efdee1d8579b.png)

**Comment by dpogue** [comment]
What version of the plugin are you using? This should be fixed in v2.0.1

**Comment by psjanwilmar** [comment]
I'm using this version "cordova-plugin-update-notifier": "^2.0.1",
![image](https://user-images.githubusercontent.com/78345816/134527253-c9dfe900-6a81-40b4-a56b-cbb61cf2294e.png)

**Comment by psjanwilmar** [comment]
solved it by going to build.gradle file and changing
`implementation "com.google.android.material:material:[1.0.0,1.5.0)"` to `implementation "com.google.android.material:material:1.5.0-alpha02"`

and it may not be necessary but i did the same to project.propperties file  and change the same values

**Comment by dpogue** [comment]
hmm, the change we made in 2.0.1 was to set `"com.google.android.material:material:[1.0.0,1.5.0)"` which should allow versions of `com.google.android.material` up to, but not including, 1.5.0. This was meant to stop it from eagerly grabbing alpha versions with breaking changes to toolset requirements.

**Comment by jpike88** [comment]
I have the same problem. A workaround is not a proper solution, please reopen the issue

**Comment by dpogue** [comment]
As of version 2.0.1, the plugin specifies `"com.google.android.material:material:[1.0.0,1.5.0)"` which should not allow using any alpha or beta version of 1.5.0 (which requires Android SDK 31, which is not currently supported by Cordova Android).

I suggest uninstalling and reinstalling v2.0.1 of this plugin to ensure it uses the correct com.google.material dependency.
