### ISSUE TITLE
Possible missing dependencies for Android

### ISSUE THREAD

**Issue by rex-iotum** [AyogoHealth/cordova-plugin-update-notifier#19]
cordova: 11
cordova-android: 10.1.1
plugin: 2.0.1

It seems like having this plugin alone didn't install the required dependencies to do Android in-app updates.
I can see the update on the play store, but the app itself doesn't react.

I only got it to prompt by installing another plugin with a build.gradle defined to load the google play core library.
https://github.com/kungfu-king-betty/cordova-plugin-native-app-update/blob/master/src/android/build.gradle

Following the exact steps, I only get the update notifier if I have the above plugin installed.

**Comment by dpogue** [comment]
That dependency should be getting added to your project automatically when the plugin is installed:
https://github.com/AyogoHealth/cordova-plugin-update-notifier/blob/7a64349344f398b460e9516d7bd6d5a86c512319/plugin.xml#L67
