### ISSUE TITLE
iOS Siren update for Notfication Center use case

### ISSUE THREAD

**Issue by laurentperez** [AyogoHealth/cordova-plugin-update-notifier#20]
Hello

In june 2022 https://github.com/ArtSabintsev/Siren/releases/tag/6.0.3 was fixed

Cocoapods says swift 5.5 does receive updates : https://cocoapods.org/pods/Siren#installation-and-integration

in plugin.xml there is 5.0

How can we guarantee to use Siren >= 6.0.3 ?

thanks

```
<platform name="ios">
    <config-file parent="/*" target="config.xml">
      <feature name="UpdateNotifier">
        <param name="ios-package" value="CDVUpdateNotifierPlugin" />
        <param name="onload" value="true" />
      </feature>

      <preference name="SwiftVersion" value="5.0" />
    </config-file>

    <source-file src="src/ios/UpdateNotifierPlugin.swift" />

    <podspec>
      <config></config>
      <pods use-frameworks="true">
        <pod name="Siren" />
      </pods>
    </podspec>
  </platform>
```

**Comment by dpogue** [comment]
Siren 6.0.0+ bumps the minimum supported iOS version to iOS 15, which is way too new for most people. Cordova-iOS supports iOS 11 and up.

From Siren's [release notes](https://github.com/ArtSabintsev/Siren/releases/tag/6.0.0):
> If you are supporting older versions of iOS, please use Siren version 5.8.1 (also found on branch `swift5.4`), which targets
> * Swift 5.4
> * iOS 13+

Cocoapods should automatically pull the latest Siren version that is compatible with your app's minimum iOS version.
