### ISSUE TITLE
How i can enable or disable ?

### ISSUE THREAD

**Issue by renatofreireda** [AyogoHealth/cordova-plugin-update-notifier#21]
I would like to know how I can enable or disable check update

**Comment by dpogue** [comment]
If you have the plugin installed, it will automatically check for updates on app launch.

Using the `SirenAlertType` and `AndroidUpdateAlertType` preferences, you have a little bit of control over how forcefully the updates are presented (either mandatory updates, or optional).

**Comment by renatofreireda** [comment]
I installed the plugin and it automatically checks when opening the app. I wanted to be able to enable or disable this check.is it possible?

**Comment by dpogue** [comment]
No, the plugin is coded so that it checks for updates immediately when launching the app. There is no JavaScript API exposed to control when the update checking happens.
