### ISSUE TITLE
Imposible close updating window

### ISSUE THREAD

**Issue by belozer-ti** [AyogoHealth/cordova-plugin-update-notifier#9]
After click on close button updating window close and opens again.

**Comment by dpogue** [comment]
Are you seeing this on iOS or Android?

**Comment by belozer-ti** [comment]
@dpogue Android 11. I tryed debug plugin. `onStart` method calls after close updating window.

**Comment by belozer-ti** [comment]
@dpogue do have any ideas for fix it?

**Comment by dpogue** [comment]
@belozer-ti It might be possible to move the update check to `pluginInitialize`, but that might also be too early or not run on the right thread.

I'm hoping to have a chance to look into this more later this week.

**Comment by belozer-ti** [comment]
@dpogue do you have updates? :)

**Comment by dpogue** [comment]
The fix is released as cordova-plugin-update-notifier@1.1.0
